name: Deploy to Github Pages

on:
  push:
    branches: [ main ]

jobs:
  publish-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm i -g yarn
      - run: yarn install --frozen-lockfile
      - run: git config user.name "Github Actions" && git config user.email "githubactions@knitlabs.org"
      - run: yarn lint
      - run: yarn build
      - run: echo knitlabs.org > dist/CNAME
      - run: yarn deploy
    env:
      GH_TOKEN: ${{secrets.SECRET_GITHUB_TOKEN}}